/*
Enter your query here.
*/
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY char_LENGTH(CITY), CITY ASC
    LIMIT 1;
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY char_LENGTH(CITY) DESC
    LIMIT 1;
